Program:
PRINT 3 * 2 ^ 4
PRINT 3 ^ (2 * 4)
PRINT 3 * (2 * 4)
PRINT 4.5 \ 1.2
PRINT 100 / 2 / 1.5 / (5.0 / 4)
PRINT 4 MOD 3 * 5
PRINT 3 * 5 MOD 4
PRINT (4 MOD 3) * 5
PRINT 3 * (5 MOD 4)
PRINT 100 - 2 - 1.5 - (5.0 - 4)
PRINT 1 < 2 <> 2 < 1
PRINT 1 <= 2 = 2 <= 1
PRINT 1 - (2 = 1 + 1)
PRINT - 1 + 2
PRINT NOT 2 < 1 AND 2 < 3
PRINT (3.0 ^ - 1) ^ 2
PRINT 3.0 ^ - 1 ^ 2
END

Executing...
48
6561
24
3
26.6667
4
3
5
3
95.5
-1
0
2
1
-1
0.111111
0.333333
